version: '3.1'

services:
  db:
    container_name: a3
    image: mysql
    restart: always
    environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: db 
    ports:
      - "3307:3306"
    volumes:
      - $PWD:/home
